global:
  name: train-abinet
  phase: train
  stage: train-supervised
  workdir: workdir
  seed: ~

dataset:
  train: {
    roots: [
        'data/STR-Fewer-Labels/training/label/real',
    ],
    batch_size: 384
  }
  valid: {
    roots: [
        'data/STR-Fewer-Labels/validation',
    ],
    batch_size: 384
  }
  test: {
    roots: [
        'data/STR-Fewer-Labels/evaluation/benchmark',
        'data/STR-Fewer-Labels/evaluation/addition',
    ],
    batch_size: 384
  }
  data_aug: True
  multiscales: False
  num_workers: 14

training:
  epochs: 50
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [ 0.9, 0.999 ], # for default Adam
  }
  scheduler: {
    periods: [ 35, 10, 5 ],
    gamma: 0.1,
  }

model:
  name: 'semimtr.modules.model_abinet_iter.ABINetIterModel'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: workdir/pretrain-vision-model/best-pretrain-vision-model.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
  language: {
    checkpoint: workdir/pretrain-language-model/pretrain-language-model.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    loss_weight: 1.,
  }
