global:
  name: consistency-regularization
  phase: train
  stage: train-semi-supervised
  workdir: workdir
  seed: ~

dataset:
  scheme: consistency_regularization
  type: ST
  train: {
    roots: [
        'data/training/label',
        'data/training/unlabel',
    ],
    batch_size: 64,
    weights: [ 0.3, 0.7 ]
  }
  valid: {
    roots: [
        'data/validation',
    ],
    batch_size: 64
  }
  test: {
    roots: [
        'data/evaluation',
    ],
    batch_size: 64
  }
  charset_path: data/charset_vn.txt
  data_aug: True
  multiscales: True #tỷ lệ khác nhau
  num_workers: 14
  augmentation_severity: 1
  case_sensitive: True
  eval_case_sensitive: True

training:
  epochs: 5
  show_iters: 100
  eval_iters: 1000
  save_iters: 1000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0001
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  scheduler: {
    periods: [ 3, 1, 1 ], 
    gamma: 0.1,
  }

model:
  name: 'semimtr.modules.model_fusion_consistency_regularization.ConsistencyRegularizationFusionModel'
  iter_size: 3
  vision: {
    checkpoint: workdir/semimtr_vision_model_real_l_and_u.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
    checkpoint_submodule: vision,
  }
  language: {
    checkpoint: workdir/abinet_language_model.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    loss_weight: 1.,
  }
  consistency: {
    loss_weight: 1.,
    supervised_flag: True,
    all_to_all: True,
    #    teacher_layer: vision,  # alignment | language | vision (doesn't matter if all_to_all is True)
    #    student_layer: all,  # all | alignment | language | vision (doesn't matter if all_to_all is True)
    teacher_one_hot: True,
    kl_div: False,
    teacher_stop_gradients: True,
    use_threshold: False,
    ema: False,
    ema_decay: 0.9999
  }
